"options":
  "postgresql-image":
    "type": "string"
    "description": "Container image for postgresql"
    "default": "docker.io/bitnami/postgresql:11.7.0-debian-10-r82"
    # "default": "rocks.canonical.com:443"
  "postgresql-pullPolicy":
    "type": "string"
    "description": "Pull policy for  postgresql container image"
    "default": "IfNotPresent"
  "postgresqlImage-pullSecrets":
    "type": "string"
    "description": "Specify docker-registry secret names as an array"
    "default": "[]"
  "postgresql-debug":
    "type": "string"
    "description": "Specify if debug logs should be enabled (true or false)"
    "default": "true"
  "postgresql-updateStrategyType":
    "type": "string"
    "description": "Statefulset update strategy policy"
    "default": "RollingUpdate"
  "postgresql-securityContext-enabled":
    "type": "boolean"
    "description": "Enable security context for Postgresql container"
    "default": true
  "postgresql-securityContext-fsGroup":
    "type": "string"
    "description": "Group ID for the Postgresql container filesystem"
    "default": "1001"
  "postgresql-securityContext-runAsUser":
    "type": "int"
    "description": "User ID for the Postgresql container"
    "default": 1001
  "postgresql-username":
    "type": "string"
    "description": "Postgresql username"
    "default": "postgres"
  "postgresql-password":
    "type": "string"
    "description": "Postgresql password"
    "default": "postgres"
  "postgresql-database":
    "type": "string"
    "description": "Postgresql database"
    "default": "postgres"
  "postgresql-replication-user":
    "type": "string"
    "description": "Postgresql replication username"
    "default": "repl_user"
  "postgresql-replication-password":
    "type": "string"
    "description": "Postgresql replication password"
    "default": "repl_password"
  "postgresql-replication-applicationName":
    "type": "string"
    "description": "Cluster application name. Useful for advanced replication settings"
    "default": "my_application"
  "postgresql-configuration":
    "type": "string"
    "description": "Runtime Config Parameters for Postgresql"
    "default": ""
  "postgresql-pgHbaConfiguration":
    "type": "string"
    "description": "Contents of pg_hba.conf"
    "default": ""
  "postgresql-configurationConfigMap":
    "type": "string"
    "description": |
      ConfigMap with the Postgresql configuration files
      (Note: Overrides postgresql-replicationConfiguration, postgresql-configuration and postgresql-pgHbaConfiguration)
    "default": ""
  "postgresql-extendedConf":
    "type": "string"
    "description": "Extended Postgresql Configuration (appended to main or default configuration)"
    "default": ""
  "postgresql-extendedConfConfigMap":
    "type": "string"
    "description": |
      ConfigMap with the extended Postgresql configuration files 
      (Note: Overrides postgresql-extendedConf)
    "default": ""
  "postgresql-initdbScripts":
    "type": "string"
    "description": "Dictionary of initdb scripts"
    "default": ""
  "postgresql-initdbScriptsConfigMap":
    "type": "string"
    "description": |
      ConfigMap with the initdb scripts (Note: Overrides initdbScripts)
      The value is evaluated as a template
    "default": ""
  "postgresql-initdbScriptsSecret":
    "type": "string"
    "description": |
      Secret with initdb scripts that contain sensitive information 
      (Note: can be used with initdbScriptsCM or initdbScripts)
      The value is evaluated as a template
    "default": ""
  "persistence-enabled":
    "type": "boolean"
    "description": "Enable data persistence"
    "default": true
