"options":
  "postgresql-image":
    "type": "string"
    "description": "Container image for postgresql"
    "default": "docker.io/bitnami/postgresql-repmgr:11.7.0-debian-10-r64"
  "postgresql-pullPolicy":
    "type": "string"
    "description": "Pull policy for  postgresql container image"
    "default": "IfNotPresent"
  "postgresql-debug":
    "type": "string"
    "description": "Specify if debug logs should be enabled (true or false)"
    "default": "true"
  "postgresql-username":
    "type": "string"
    "description": "Postgresql username"
    "default": "postgres"
  "postgresql-password":
    "type": "string"
    "description": "Postgresql password"
    "default": "postgres"
  "postgresql-database":
    "type": "string"
    "description": "Postgresql database"
    "default": "postgres"
  "postgresql-repmgr-username":
    "type": "string"
    "description": "Postgresql repmgr username"
    "default": "repmgr"
  "postgresql-repmgr-password":
    "type": "string"
    "description": "Postgresql repmgr password"
    "default": "repmgr"
  "postgresql-repmgr-database":
    "type": "string"
    "description": "PostgreSQL repmgr database"
    "default": "repmgr"
  "metrics-image":
    "type": "string"
    "description": "Container image for PostgreSQL Prometheus exporter"
    "default": "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r66"
  "metrics-pullPolicy":
    "type": "string"
    "description": "Pull policy for  PostgreSQL Prometheus exporter"
    "default": "IfNotPresent"
